autoconf better supported

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -799,23 +799,28 @@ fi
 
 
 
-echo $ac_n "checking for main in -ljpeg""... $ac_c" 1>&6
-echo "configure:804: checking for main in -ljpeg" >&5
-ac_lib_var=`echo jpeg'_'main | sed 'y%./+-%__p_%'`
+
+echo $ac_n "checking for jpeg_read_header in -ljpeg""... $ac_c" 1>&6
+echo "configure:805: checking for jpeg_read_header in -ljpeg" >&5
+ac_lib_var=`echo jpeg'_'jpeg_read_header | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
 LIBS="-ljpeg  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 812 "configure"
+#line 813 "configure"
 #include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char jpeg_read_header();
 
 int main() {
-main()
+jpeg_read_header()
 ; return 0; }
 EOF
-if { (eval echo configure:819: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:824: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -840,11 +845,17 @@ EOF
 
 else
   echo "$ac_t""no" 1>&6
+
+echo "Cannot find libjpeg or you have too old version (v6 or later required)."
+exit 1
+
 fi
 
 
+
+
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:848: checking how to run the C preprocessor" >&5
+echo "configure:859: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -859,13 +870,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 863 "configure"
+#line 874 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:869: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:880: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   :
@@ -876,13 +887,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 880 "configure"
+#line 891 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:886: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:897: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   :
@@ -905,12 +916,12 @@ fi
 echo "$ac_t""$CPP" 1>&6
 
 echo $ac_n "checking for ANSI C header files""... $ac_c" 1>&6
-echo "configure:909: checking for ANSI C header files" >&5
+echo "configure:920: checking for ANSI C header files" >&5
 if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 914 "configure"
+#line 925 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -918,7 +929,7 @@ else
 #include <float.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:922: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:933: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -935,7 +946,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 939 "configure"
+#line 950 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -953,7 +964,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 957 "configure"
+#line 968 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -974,7 +985,7 @@ if test "$cross_compiling" = yes; then
   :
 else
   cat > conftest.$ac_ext <<EOF
-#line 978 "configure"
+#line 989 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -985,7 +996,7 @@ if (XOR (islower (i), ISLOWER (i)) || toupper (i) != TOUPPER (i)) exit(2);
 exit (0); }
 
 EOF
-if { (eval echo configure:989: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1000: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -1012,17 +1023,17 @@ for ac_hdr in unistd.h getopt.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:1016: checking for $ac_hdr" >&5
+echo "configure:1027: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1021 "configure"
+#line 1032 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1026: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1037: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1048,10 +1059,54 @@ else
 fi
 done
 
+for ac_hdr in jpeglib.h
+do
+ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
+echo "configure:1067: checking for $ac_hdr" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1072 "configure"
+#include "confdefs.h"
+#include <$ac_hdr>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1077: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&6
+echo "Cannot find jpeglib.h  You need libjpeg v6 or later."
+exit 1
+
+fi
+done
+
+
 
 
 echo $ac_n "checking size of long""... $ac_c" 1>&6
-echo "configure:1055: checking size of long" >&5
+echo "configure:1110: checking size of long" >&5
 if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1059,7 +1114,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1063 "configure"
+#line 1118 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1070,7 +1125,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1074: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1129: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long=`cat conftestval`
 else
@@ -1090,7 +1145,7 @@ EOF
 
 
 echo $ac_n "checking size of int""... $ac_c" 1>&6
-echo "configure:1094: checking size of int" >&5
+echo "configure:1149: checking size of int" >&5
 if eval "test \"`echo '$''{'ac_cv_sizeof_int'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1098,7 +1153,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1102 "configure"
+#line 1157 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1109,7 +1164,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1113: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1168: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_int=`cat conftestval`
 else
@@ -1134,12 +1189,12 @@ EOF
 for ac_func in getopt_long
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:1138: checking for $ac_func" >&5
+echo "configure:1193: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1143 "configure"
+#line 1198 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1162,7 +1217,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1166: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1221: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1186,6 +1241,50 @@ else
 fi
 done
 
+
+
+
+echo $ac_n "checking for broken jmorecfg.h (METHODDEF)""... $ac_c" 1>&6
+echo "configure:1249: checking for broken jmorecfg.h (METHODDEF)" >&5
+if eval "test \"`echo '$''{'jpeginfo_cv_broken_methoddef'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test "$cross_compiling" = yes; then
+  jpeginfo_cv_broken_methoddef=no
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1257 "configure"
+#include "confdefs.h"
+
+#include <stdio.h>
+#include <jpeglib.h>
+METHODDEF(void) foo(void) { };
+int main(void)
+{
+  return 0;
+}
+EOF
+if { (eval echo configure:1268: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+then
+  jpeginfo_cv_broken_methoddef=no
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  jpeginfo_cv_broken_methoddef=yes
+fi
+rm -fr conftest*
+fi
+
+fi
+
+if test $jpeginfo_cv_broken_methoddef = yes; then
+  cat >> confdefs.h <<\EOF
+#define BROKEN_METHODDEF 1
+EOF
+
+fi
+echo "$ac_t""$jpeginfo_cv_broken_methoddef" 1>&6
 
 
 trap '' 1 2 15
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,3 +1,5 @@
+dnl $Id$
+dnl 
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(jpeginfo.c)
 AC_CONFIG_HEADER(config.h)
@@ -10,12 +12,22 @@ AC_PROG_MAKE_SET
 
 
 dnl Checks for libraries.
-dnl Replace `main' with a function in -ljpeg:
-AC_CHECK_LIB(jpeg, main)
+
+AC_CHECK_LIB(jpeg, jpeg_read_header, ,[
+echo "Cannot find libjpeg or you have too old version (v6 or later required)."
+exit 1
+])
+
 
 dnl Checks for header files.
+
 AC_HEADER_STDC
 AC_CHECK_HEADERS(unistd.h getopt.h)
+AC_CHECK_HEADERS(jpeglib.h, ,[
+echo "Cannot find jpeglib.h  You need libjpeg v6 or later."
+exit 1
+])
+
 
 dnl Checks for typedefs, structures, and compiler characteristics.
 
@@ -26,6 +38,27 @@ AC_CHECK_SIZEOF(int)
 
 dnl Checks for library functions.
 AC_CHECK_FUNCS(getopt_long)
+
+
+dnl own tests
+
+AC_MSG_CHECKING([for broken jmorecfg.h (METHODDEF)])
+AC_CACHE_VAL(jpeginfo_cv_broken_methoddef,
+[AC_TRY_RUN([
+#include <stdio.h>
+#include <jpeglib.h>
+METHODDEF(void) foo(void) { };
+int main(void)
+{
+  return 0;
+}],
+jpeginfo_cv_broken_methoddef=no,
+jpeginfo_cv_broken_methoddef=yes,
+jpeginfo_cv_broken_methoddef=no)])
+if test $jpeginfo_cv_broken_methoddef = yes; then
+  AC_DEFINE(BROKEN_METHODDEF)
+fi
+AC_MSG_RESULT($jpeginfo_cv_broken_methoddef)
 
 
 AC_OUTPUT(Makefile)
